## ADD WHATEVER ARGUMENTS ARE NECESSARY TO THE MAIN FUNCTION
def main() :
    d = 0 ## VARIABLE 'd' SHOULD STORE THE NUMBER OF DINUCLEOTIDES

    ## YOU CODE SHOULD START HERE!!

    ## YOU CODE SHOULD END HERE!!

    ## DO NOT REMOVE THIS LINE, IT SHOULD RETURN THE NUMBER OF DINUCLEOTIDES
    return(d)

## DO NOT REMOVE THIS LINE BELOW
if __name__ == "__main__" :

    ## MODIFY THE LINE BELOW AND ADD BEFORE WHATEVER LINES ARE NECESSARY
    ## TO RUN THIS PROGRAM AS:
    ## $ python src/dinuc.py HBB.fa A A
    ## WHERE THE FIRST ARGUMENT IS A FASTA FILENAME AND THE SECOND AND
    ## THIRD ARGUMENTS ARE THE FIRST AND SECOND NUCLEOTIDES OF THE
    ## SOUGHT DINUCLEOTIDE
    print(main())
